using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class Booking1
    {
        public int ImportId { get; set; }
        public string? SoNumber { get; set; }
        public int? SoLineNum { get; set; }
        public DateTime? BookedDate { get; set; }
        public string? SoTypeKey { get; set; }
        public string? SoType { get; set; }
        public string? PoType { get; set; }
        public string? CustomerPo { get; set; }
        public string? MaterialKey { get; set; }
        public string? Material { get; set; }
        public string? MaterialEccn { get; set; }
        public string? MaterialHts { get; set; }
        public string? MaterialMedium { get; set; }
        public int? BookingQty { get; set; }
        public double? BookingNetValue { get; set; }
        public string? DeliveryStatus { get; set; }
        public string? CompleteDelivery { get; set; }
        public string? ResasonCode { get; set; }
        public string? Compliance { get; set; }
        public string? EmbargoLineStatus { get; set; }
        public DateTime? ScheduleLineDate { get; set; }
        public string? SoSchedLineNo { get; set; }
        public string? SalesDocItemCat { get; set; }
        public string? GtsOverallStatus { get; set; }
        public string? LicenseBlocked { get; set; }
        public string? SplLineStatus { get; set; }
        public string? Mit { get; set; }
        public string? Incoterms1 { get; set; }
        public string? Incoterms2 { get; set; }
        public string? RtphStatus { get; set; }
        public string? ShippingType { get; set; }
        public string? EuKey { get; set; }
        public string? EndUser { get; set; }
        public string? EuStreet1 { get; set; }
        public string? EuStreet2 { get; set; }
        public string? EuStreet3 { get; set; }
        public string? EuStreet4 { get; set; }
        public string? EuLocation { get; set; }
        public string? EuPostalCode { get; set; }
        public string? EuCountryCode { get; set; }
        public string? EuCountry { get; set; }
        public string? BilltoBusinessPartner { get; set; }
        public string? BilltoName { get; set; }
        public string? BilltoStreet1 { get; set; }
        public string? BilltoStreet2 { get; set; }
        public string? BilltoStreet3 { get; set; }
        public string? BilltoStreet4 { get; set; }
        public string? BilltoLoc { get; set; }
        public string? BilltoPostalCode { get; set; }
        public string? BilltoStreetCountry { get; set; }
        public string? ShiptoBusinessPartner { get; set; }
        public string? ShiptoName { get; set; }
        public string? ShiptoStreet1 { get; set; }
        public string? ShiptoStreet2 { get; set; }
        public string? ShiptoStreet3 { get; set; }
        public string? ShiptoStreet4 { get; set; }
        public string? ShiptoLoc { get; set; }
        public string? ShiptoPostalCode { get; set; }
        public string? ShiptoCountry { get; set; }
        public string? SoldtoBusinessPartner { get; set; }
        public string? SoldtoName { get; set; }
        public string? SoldtoStreet1 { get; set; }
        public string? SoldtoStreet2 { get; set; }
        public string? SoldtoStreet3 { get; set; }
        public string? SoldtoStreet4 { get; set; }
        public string? SoldtoLoc { get; set; }
        public string? SoldtoPostalCode { get; set; }
        public string? SoldtoCountry { get; set; }
        public string? MaterialPlantCountryOrig { get; set; }
        public string? Plant { get; set; }
        public string? PlantMedium { get; set; }
        public string? PlantCountry { get; set; }
        public string? Payer { get; set; }
        public string? FrieghtForwarder1 { get; set; }
        public string? FrieghtForwarder1Street1 { get; set; }
        public string? FrieghtForwarder1Street2 { get; set; }
        public string? FrieghtForwarder1Street3 { get; set; }
        public string? FrieghtForwarder1Street4 { get; set; }
        public string? FrieghtForwarder1Loc { get; set; }
        public string? FrieghtForwarder1Country { get; set; }
        public string? FrieghtForwarder2 { get; set; }
        public string? FrieghtForwarder2Street1 { get; set; }
        public string? FrieghtForwarder2Street2 { get; set; }
        public string? FrieghtForwarder2Street3 { get; set; }
        public string? FrieghtForwarder2Street4 { get; set; }
        public string? FrieghtForwarder2Loc { get; set; }
        public string? FrieghtForwarder2Country { get; set; }
        public string? FrieghtForwarder3 { get; set; }
        public string? FrieghtForwarder3Street1 { get; set; }
        public string? FrieghtForwarder3Street2 { get; set; }
        public string? FrieghtForwarder3Street3 { get; set; }
        public string? FrieghtForwarder3Street4 { get; set; }
        public string? FrieghtForwarder3Loc { get; set; }
        public string? FrieghtForwarder3Country { get; set; }
        public string? ShippingNote { get; set; }
        public DateTime? ImportDate { get; set; }
        public string? ImportStatus { get; set; }
    }
}
