using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class BookingsMay2018
    {
        public string? SalesOrderNumber { get; set; }
        public string? BookDate0createdon { get; set; }
        public string? OrderType1 { get; set; }
        public string? OrderType2 { get; set; }
        public string? ReasonCode { get; set; }
        public string? Compliance { get; set; }
        public string? SalesDocumentItemCategory { get; set; }
        public string? DeliveryStatus { get; set; }
        public string? CompleteDelivery { get; set; }
        public string? EmbargoStatusAtTheLineLevel { get; set; }
        public string? GtsOverallStatus { get; set; }
        public string? LicenseForBlocked { get; set; }
        public string? SplStatusAtTheLineLevel { get; set; }
        public string? Mit { get; set; }
        public string? PurchaseOrderType { get; set; }
        public string? MaterialKey { get; set; }
        public string? Material { get; set; }
        public string? MaterialEccnKey { get; set; }
        public string? MaterialHtsKey { get; set; }
        public string? MaterialMediumKey { get; set; }
        public string? Incoterms1 { get; set; }
        public string? Incoterms2 { get; set; }
        public string? RtphStatus { get; set; }
        public string? ShippingType { get; set; }
        public string? EndUserKey { get; set; }
        public string? EndUser { get; set; }
        public string? EndUserStreetNameKey { get; set; }
        public string? EndUserBasStreet2Key { get; set; }
        public string? EndUserBasStreet3Key { get; set; }
        public string? EndUserBasStreet4Key { get; set; }
        public string? EndUserLocationKey { get; set; }
        public string? EndUserBasPostalCodeKey { get; set; }
        public string? EndUserCountryKey { get; set; }
        public string? EndUserCountryText { get; set; }
        public string? BillToPartyBusinessPartnerKey { get; set; }
        public string? BillToPartyNameKey { get; set; }
        public string? BillToPartyStreetNameKey { get; set; }
        public string? BillToPartyBasStreet2Key { get; set; }
        public string? BillToPartyBasStreet3Key { get; set; }
        public string? BillToPartyBasStreet4Key { get; set; }
        public string? BillToPartyLocationKey { get; set; }
        public string? BillToPartyBasPostalCodeKey { get; set; }
        public string? BillToPartyCountryText { get; set; }
        public string? ShipToPartyBusinessPartnerKey { get; set; }
        public string? ShipToPartyNameKey { get; set; }
        public string? ShipToPartyStreetNameKey { get; set; }
        public string? ShipToPartyBasStreet2Key { get; set; }
        public string? ShipToPartyBasStreet3Key { get; set; }
        public string? ShipToPartyBasStreet4Key { get; set; }
        public string? ShipToPartyLocationKey { get; set; }
        public string? ShipToPartyBasPostalCodeKey { get; set; }
        public string? ShipToPartyCountryText { get; set; }
        public string? SoldToPartyBusinessPartnerKey { get; set; }
        public string? SoldToPartyNameKey { get; set; }
        public string? SoldToPartyStreetNameKey { get; set; }
        public string? SoldToPartyBasStreet2Key { get; set; }
        public string? SoldToPartyBasStreet3Key { get; set; }
        public string? SoldToPartyBasStreet4Key { get; set; }
        public string? SoldToPartyLocationKey { get; set; }
        public string? SoldToPartyBasPostalCodeKey { get; set; }
        public string? SoldToPartyCountryText { get; set; }
        public string? MaterialPlantViewCountryOfOriginText { get; set; }
        public string? PlantKey { get; set; }
        public string? PlantMediumText { get; set; }
        public string? PlantCountryKey { get; set; }
        public string? SalesOrderLineItem { get; set; }
        public string? ScheduleLineDate { get; set; }
        public string? SalesOrderScheduleLineNo { get; set; }
        public string? BookingQuantity { get; set; }
        public string? BookingsNetValue { get; set; }
        public string? CustomerPoNumber { get; set; }
        public string? PayerKey { get; set; }
        public string? FrieghtForwarder1 { get; set; }
        public string? FrieghtForwarder1StreetNameKey { get; set; }
        public string? FrieghtForwarder1BasStreet2Key { get; set; }
        public string? FrieghtForwarder1BasStreet3Key { get; set; }
        public string? FrieghtForwarder1BasStreet4Key { get; set; }
        public string? FrieghtForwarder1LocationKey { get; set; }
        public string? FrieghtForwarder1CountryText { get; set; }
        public string? FrieghtForwarder2 { get; set; }
        public string? FrieghtForwarder2StreetNameKey { get; set; }
        public string? FrieghtForwarder2BasStreet2Key { get; set; }
        public string? FrieghtForwarder2BasStreet3Key { get; set; }
        public string? FrieghtForwarder2BasStreet4Key { get; set; }
        public string? FrieghtForwarder2LocationKey { get; set; }
        public string? FrieghtForwarder2CountryText { get; set; }
        public string? FrieghtForwarder3 { get; set; }
        public string? FrieghtForwarder3StreetNameKey { get; set; }
        public string? FrieghtForwarder3BasStreet2Key { get; set; }
        public string? FrieghtForwarder3BasStreet3Key { get; set; }
        public string? FrieghtForwarder3BasStreet4Key { get; set; }
        public string? FrieghtForwarder3LocationKey { get; set; }
        public string? FrieghtForwarder3CountryText { get; set; }
        public string? QuoteId { get; set; }
    }
}
