using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class LampRma
    {
        public int ImportId { get; set; }
        public string? ComplaintsNo { get; set; }
        public int? RmaItemNumber { get; set; }
        public string? HeaderStatus { get; set; }
        public string? ItemStatus { get; set; }
        public DateTime? RmaCreateDate { get; set; }
        public DateTime? ItemCreateDate { get; set; }
        public string? ValuationType { get; set; }
        public string? RmaItemType { get; set; }
        public string? RmaItemTypeKey { get; set; }
        public string? ServiceReqNo { get; set; }
        public string? DefectSerialNo { get; set; }
        public string? DefectProductIdKey { get; set; }
        public string? DefectProductId { get; set; }
        public string? DefectProductIdEccnKey { get; set; }
        public string? DefectProductIdHtsKey { get; set; }
        public string? DefectProductIdOverLengthPartNumKey { get; set; }
        public string? ReplaceSerialNo { get; set; }
        public string? ReplaceProductIdKey { get; set; }
        public string? ReplaceProductId { get; set; }
        public string? ReplaceProductIdEccnKey { get; set; }
        public string? ReplaceProductIdHtsKey { get; set; }
        public string? ReplaceProductIdOverLengthPartNumKey { get; set; }
        public string? PlantKey { get; set; }
        public string? PlantText { get; set; }
        public string? StorageLocationKey { get; set; }
        public string? StorageLocationText { get; set; }
        public string? EndCustomerKey { get; set; }
        public string? EndCustomerName { get; set; }
        public string? EndCustomerStreet1 { get; set; }
        public string? EndCustomerStreet2 { get; set; }
        public string? EndCustomerStreet3 { get; set; }
        public string? EndCustomerStreet4 { get; set; }
        public string? EndCustomerCity { get; set; }
        public string? EndCustomerRegion { get; set; }
        public string? EndCustomerCountryCode { get; set; }
        public string? EndCustomerCountry { get; set; }
        public string? EndCustomerPostalCode { get; set; }
        public string? AssociatedContactKey { get; set; }
        public string? AssociatedContactName { get; set; }
        public string? AssociatedContactStreet1 { get; set; }
        public string? AssociatedContactStreet2 { get; set; }
        public string? AssociatedContactStreet3 { get; set; }
        public string? AssociatedContactStreet4 { get; set; }
        public string? AssociatedContactCity { get; set; }
        public string? AssociatedContactRegion { get; set; }
        public string? AssociatedContactCountryCode { get; set; }
        public string? AssociatedContactCountry { get; set; }
        public string? AssociatedContactPostalCode { get; set; }
        public DateTime? ShipDate { get; set; }
        public string? TrackingNo { get; set; }
        public string? ShipToSiteKey { get; set; }
        public string? ShiptoSiteName { get; set; }
        public string? ShiptoAddr1 { get; set; }
        public string? ShiptoAddr2 { get; set; }
        public string? ShiptoCity { get; set; }
        public string? ShiptoSiteRegionKey { get; set; }
        public string? ShiptoSiteRegion { get; set; }
        public string? ShiptoSiteCountryCode { get; set; }
        public string? ShiptoSitePostalCode { get; set; }
        public string? InstalledAtKey { get; set; }
        public string? InstalledAtName { get; set; }
        public string? InstalledAtBasStreet1 { get; set; }
        public string? InstalledAtBasStreet2 { get; set; }
        public string? InstalledAtBasStreet3 { get; set; }
        public string? InstalledAtBasStreet4 { get; set; }
        public string? InstalledAtCity { get; set; }
        public string? InstalledAtRegion { get; set; }
        public string? InstalledAtCountryCode { get; set; }
        public string? InstalledAtCountry { get; set; }
        public string? InstalledAtPostalCode { get; set; }
        public string? CustomsDeclarationNo { get; set; }
        public string? CustomsDeclCreateDt { get; set; }
        public string? Coo { get; set; }
        public string? DeliveryNumber { get; set; }
        public DateTime? DeliveryCreateDate { get; set; }
        public string? LegalRegulation { get; set; }
        public DateTime? LicenseValidFrom { get; set; }
        public DateTime? LicenseValidTo { get; set; }
        public DateTime? LicenseAppliedDate { get; set; }
        public string? LicenseNumber { get; set; }
        public string? LicenseType { get; set; }
        public string? ExtLicence { get; set; }
        public string? GoodsSupplier { get; set; }
        public string? GoodsSupplierKey { get; set; }
        public string? Vendor { get; set; }
        public string? VendorKey { get; set; }
        public string? ShiptoPartyKey { get; set; }
        public string? GtsShipto { get; set; }
        public string? GtsShiptoAddr { get; set; }
        public string? GtsShiptoAddr1 { get; set; }
        public string? GtsShiptoAddr2 { get; set; }
        public string? GtsShiptoCity { get; set; }
        public string? GtsShiptoCountry { get; set; }
        public string? BilltoPartyKey { get; set; }
        public string? GtsBillto { get; set; }
        public string? GtsBilltoAddr { get; set; }
        public string? GtsBilltoAddr1 { get; set; }
        public string? GtsBilltoAddr2 { get; set; }
        public string? GtsBilltoCity { get; set; }
        public string? GtsBilltoCountry { get; set; }
        public string? ExporterKey { get; set; }
        public string? ExporterAddr { get; set; }
        public string? ExporterAddr1 { get; set; }
        public string? ExporterAddr2 { get; set; }
        public string? ExporterCity { get; set; }
        public string? ExporterCountry { get; set; }
        public string? CustomsValuation { get; set; }
        public DateTime? ImportDate { get; set; }
        public string? ImportStatus { get; set; }
    }
}
