using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class PartnerAnalyzerDistiStck
    {
        public double? ItemNumber { get; set; }
        public DateTime? SaleDate { get; set; }
        public string? ClaimStatus { get; set; }
        public string? CiStatus { get; set; }
        public string? SalesOrderNumber { get; set; }
        public string? DistributorSalesOrPdisslsonKey { get; set; }
        public string? ProductSnPos { get; set; }
        public string? TransmissionNumber { get; set; }
        public string? SdContractNumber { get; set; }
        public string? EndCustomerKey { get; set; }
        public string? EndCustomerPos { get; set; }
        public string? EndCustomerBasStreetKey { get; set; }
        public string? EndCustomerBasStreet2Key { get; set; }
        public string? EndCustomerBasStreet3Key { get; set; }
        public string? EndCustomerBasStreet4Key { get; set; }
        public string? PosEndCustomerBasDistrictKey { get; set; }
        public string? EndCustomerBasPostalCodeKey { get; set; }
        public string? EndCustomerRegionKey { get; set; }
        public string? PosEndCustomerCountryKey { get; set; }
        public string? EndCustomerCountryPos { get; set; }
        public string? PosBillToPartyKey { get; set; }
        public string? PosBillToPartyLongText { get; set; }
        public string? BillToPartyBasStreetKey { get; set; }
        public string? BillToPartyBasStreet2Key { get; set; }
        public string? BillToPartyBasStreet3Key { get; set; }
        public string? BillToPartyBasStreet4Key { get; set; }
        public string? PosBillToPartyBasDistrictKey { get; set; }
        public string? BillToPartyRegionKey { get; set; }
        public string? BillToPartyBasPostalCodeKey { get; set; }
        public string? PosBillToPartyCountryText { get; set; }
        public string? ChannelPartnerKey { get; set; }
        public double? DistributorKey { get; set; }
        public string? DistributorLongText { get; set; }
        public string? DistributorBasStreetKey { get; set; }
        public string? DistributorBasStreet2Key { get; set; }
        public string? DistributorBasStreet3Key { get; set; }
        public string? DistributorBasStreet4Key { get; set; }
        public string? DistributorRegionKey { get; set; }
        public string? DistributorDistrictKey { get; set; }
        public string? DistributorBasPostalCodeKey { get; set; }
        public string? DistributorCountryText { get; set; }
        public double? Reseller1Key { get; set; }
        public string? ResellerNamePos { get; set; }
        public string? Reseller1BasStreetKey { get; set; }
        public string? Reseller1BasStreet2Key { get; set; }
        public string? Reseller1BasStreet3Key { get; set; }
        public DateTime? Reseller1BasStreet4Key { get; set; }
        public string? Reseller1BasDistrictKey { get; set; }
        public string? Reseller1BasPostalCodeKey { get; set; }
        public string? ResellerCountryPos { get; set; }
        public string? DocumentOrderNumbe { get; set; }
        public string? ProductIdPos { get; set; }
        public string? Material { get; set; }
        public string? MaterialProductCategoryText { get; set; }
        public string? MaterialMaterialTypeKey { get; set; }
        public string? MaterialMaterialTypeText { get; set; }
        public string? PosMaterialEccnKey { get; set; }
        public string? PosMaterialHtsKey { get; set; }
        public double? TransactionQuantity { get; set; }
        public double? ReportedQuantity { get; set; }
        public double? JuniperPosValue { get; set; }
        public double? ClaimAmount { get; set; }
        public string? TransactionDate { get; set; }
        public DateTime? ResaleShipDate { get; set; }
        public string? ResellerPoNumber { get; set; }
        public string? EndCustomerPoNumber { get; set; }
        public string? ContractNumber { get; set; }
        public string? ServiceContractType { get; set; }
        public string? ContractItemNo { get; set; }
        public DateTime? ContractCreationDate { get; set; }
        public string? ContractStatusText { get; set; }
        public DateTime? ServiceStartDate { get; set; }
        public DateTime? ServiceEndDate { get; set; }
        public string? SalesOrderAlpha { get; set; }
        public string? InstalledAtKey { get; set; }
        public string? InstalledAtLongText { get; set; }
        public string? InstalledAtBasDistrictText { get; set; }
        public string? InstalledAtCountryKey { get; set; }
        public string? EndCustomer { get; set; }
        public string? EndCustomerServices { get; set; }
        public string? SvcmrgEndCustomerBasDistrictKey { get; set; }
        public string? EndCustomerCountryServices { get; set; }
        public string? SvcmrgBillToPartyKey { get; set; }
        public string? SvcmrgBillToPartyLongText { get; set; }
        public string? SvcmrgBillToPartyBasDistrictKey { get; set; }
        public string? SvcmrgBillToPartyCountryText { get; set; }
        public string? PayerKey { get; set; }
        public string? PayerLongText { get; set; }
        public string? PayerBasDistrictKey { get; set; }
        public string? PayerCountryText { get; set; }
        public string? ProductIdServices { get; set; }
        public string? MaterialText { get; set; }
        public string? ServiceMaterialKey { get; set; }
        public string? ServiceMaterial { get; set; }
        public string? ServiceMaterialProductLineText { get; set; }
        public string? ProductLine { get; set; }
        public string? ProductFamily { get; set; }
        public string? SvcmrgMaterialEccnKey { get; set; }
        public string? SvcmrgMaterialHtsKey { get; set; }
        public string? IObjectId { get; set; }
        public string? SerialNumber { get; set; }
        public string? ContractLineItemStatusDescription { get; set; }
        public string? Currency { get; set; }
        public string? ExtendedListPriceDoNotUse { get; set; }
        public string? DiscountDoNotUse { get; set; }
        public string? NetValue { get; set; }
        public double? NetValueOfTheSo { get; set; }
        public double? _2016ListPrice { get; set; }
        public double? DiscountGiven { get; set; }
        public double? DiscountGiven1 { get; set; }
        public double? DiscountBySvcECAvgDiscountByCountry { get; set; }
        public double? DiscountShouldHaveBasedOnAvgDscntByCty { get; set; }
        public double? DiscountShouldHaveBasedOnStD37 { get; set; }
    }
}
