using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class Profiled2016
    {
        public string? ProfileDate { get; set; }
        public string? GtsId { get; set; }
        public string? AccountName { get; set; }
        public string? AddressLine1 { get; set; }
        public string? AddressLine2 { get; set; }
        public string? AddressLine3 { get; set; }
        public string? AddressLine4 { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? CountryCode { get; set; }
        public string? PostalCode { get; set; }
        public string? Elr { get; set; }
        public string? S3Gov { get; set; }
        public string? Ns3Gov { get; set; }
        public string? GovEndUse { get; set; }
        public string? GovExempt { get; set; }
        public string? EpciConcern { get; set; }
        public string? EpciExemptEuca { get; set; }
        public string? EpciExemptEucnr { get; set; }
        public string? EpciEucr { get; set; }
        public string? DiversionRisk { get; set; }
        public string? DiversionNotRisk { get; set; }
        public string? SystemIntegrator { get; set; }
        public string? ServiceProvider { get; set; }
        public string? PotentialEmbargo { get; set; }
        public string? TradingEntity { get; set; }
        public string? ProfiledGovRelated { get; set; }
        public string? ProfiledNogovNosoe { get; set; }
        public string? NotProfiledRiskyCnty { get; set; }
        public string? NotProfiledNonriskyCnty { get; set; }
        public string? ProfiledCommercialSelltoGov { get; set; }
        public string? Column31 { get; set; }
        public string? Column32 { get; set; }
        public string? Column33 { get; set; }
        public string? Column34 { get; set; }
        public string? Column35 { get; set; }
        public string? Column36 { get; set; }
        public string? Column37 { get; set; }
        public string? Column38 { get; set; }
        public string? Column39 { get; set; }
        public string? Column40 { get; set; }
        public string? Column41 { get; set; }
        public string? Column42 { get; set; }
        public string? Column43 { get; set; }
        public string? Column44 { get; set; }
        public string? Column45 { get; set; }
        public string? Column46 { get; set; }
        public string? Column47 { get; set; }
        public string? Column48 { get; set; }
        public string? Column49 { get; set; }
        public string? Column50 { get; set; }
        public string? Column51 { get; set; }
        public string? Column52 { get; set; }
        public string? Column53 { get; set; }
        public string? Column54 { get; set; }
        public string? Column55 { get; set; }
        public string? Column56 { get; set; }
        public string? Column57 { get; set; }
        public string? Column58 { get; set; }
        public string? Column59 { get; set; }
        public string? Column60 { get; set; }
        public string? Column61 { get; set; }
        public string? Column62 { get; set; }
        public string? Column63 { get; set; }
        public string? Column64 { get; set; }
        public string? Column65 { get; set; }
        public string? Column66 { get; set; }
        public string? Column67 { get; set; }
        public string? Column68 { get; set; }
        public string? Column69 { get; set; }
        public string? Column70 { get; set; }
        public string? Column71 { get; set; }
        public string? Column72 { get; set; }
        public string? Column73 { get; set; }
        public string? Column74 { get; set; }
        public string? Column75 { get; set; }
        public string? Column76 { get; set; }
        public string? Column77 { get; set; }
        public string? Column78 { get; set; }
        public string? Column79 { get; set; }
        public string? Column80 { get; set; }
        public string? Column81 { get; set; }
        public string? Column82 { get; set; }
        public string? Column83 { get; set; }
        public string? Column84 { get; set; }
        public string? Column85 { get; set; }
        public string? Column86 { get; set; }
        public string? Column87 { get; set; }
        public string? Column88 { get; set; }
        public string? Column89 { get; set; }
        public string? Column90 { get; set; }
        public string? Column91 { get; set; }
        public string? Column92 { get; set; }
        public string? Column93 { get; set; }
        public string? Column94 { get; set; }
        public string? Column95 { get; set; }
        public string? Column96 { get; set; }
        public string? Column97 { get; set; }
        public string? Column98 { get; set; }
        public string? Column99 { get; set; }
        public string? Column100 { get; set; }
        public string? Column101 { get; set; }
        public string? Column102 { get; set; }
        public string? Column103 { get; set; }
        public string? Column104 { get; set; }
        public string? Column105 { get; set; }
        public string? Column106 { get; set; }
        public string? Column107 { get; set; }
        public string? Column108 { get; set; }
        public string? Column109 { get; set; }
        public string? Column110 { get; set; }
        public string? Column111 { get; set; }
        public string? Column112 { get; set; }
        public string? Column113 { get; set; }
        public string? Column114 { get; set; }
        public string? Column115 { get; set; }
        public string? Column116 { get; set; }
        public string? Column117 { get; set; }
        public string? Column118 { get; set; }
        public string? Column119 { get; set; }
        public string? Column120 { get; set; }
        public string? Column121 { get; set; }
        public string? Column122 { get; set; }
        public string? Column123 { get; set; }
        public string? Column124 { get; set; }
        public string? Column125 { get; set; }
        public string? Column126 { get; set; }
        public string? Column127 { get; set; }
        public string? Column128 { get; set; }
        public string? Column129 { get; set; }
        public string? Column130 { get; set; }
        public string? Column131 { get; set; }
        public string? Column132 { get; set; }
        public string? Column133 { get; set; }
        public string? Column134 { get; set; }
        public string? Column135 { get; set; }
        public string? Column136 { get; set; }
        public string? Column137 { get; set; }
        public string? Column138 { get; set; }
        public string? Column139 { get; set; }
        public string? Column140 { get; set; }
        public string? Column141 { get; set; }
        public string? Column142 { get; set; }
        public string? Column143 { get; set; }
        public string? Column144 { get; set; }
        public string? Column145 { get; set; }
        public string? Column146 { get; set; }
        public string? Column147 { get; set; }
        public string? Column148 { get; set; }
        public string? Column149 { get; set; }
        public string? Column150 { get; set; }
        public string? Column151 { get; set; }
        public string? Column152 { get; set; }
        public string? Column153 { get; set; }
        public string? Column154 { get; set; }
        public string? Column155 { get; set; }
        public string? Column156 { get; set; }
        public string? Column157 { get; set; }
        public string? Column158 { get; set; }
        public string? Column159 { get; set; }
        public string? Column160 { get; set; }
        public string? Column161 { get; set; }
        public string? Column162 { get; set; }
        public string? Column163 { get; set; }
        public string? Column164 { get; set; }
        public string? Column165 { get; set; }
        public string? Column166 { get; set; }
        public string? Column167 { get; set; }
        public string? Column168 { get; set; }
        public string? Column169 { get; set; }
        public string? Column170 { get; set; }
        public string? Column171 { get; set; }
        public string? Column172 { get; set; }
        public string? Column173 { get; set; }
        public string? Column174 { get; set; }
        public string? Column175 { get; set; }
        public string? Column176 { get; set; }
        public string? Column177 { get; set; }
        public string? Column178 { get; set; }
        public string? Column179 { get; set; }
        public string? Column180 { get; set; }
        public string? Column181 { get; set; }
        public string? Column182 { get; set; }
        public string? Column183 { get; set; }
        public string? Column184 { get; set; }
        public string? Column185 { get; set; }
        public string? Column186 { get; set; }
        public string? Column187 { get; set; }
        public string? Column188 { get; set; }
        public string? Column189 { get; set; }
        public string? Column190 { get; set; }
        public string? Column191 { get; set; }
        public string? Column192 { get; set; }
        public string? Column193 { get; set; }
        public string? Column194 { get; set; }
        public string? Column195 { get; set; }
        public string? Column196 { get; set; }
        public string? Column197 { get; set; }
        public string? Column198 { get; set; }
        public string? Column199 { get; set; }
        public string? Column200 { get; set; }
        public string? Column201 { get; set; }
        public string? Column202 { get; set; }
        public string? Column203 { get; set; }
        public string? Column204 { get; set; }
        public string? Column205 { get; set; }
        public string? Column206 { get; set; }
        public string? Column207 { get; set; }
        public string? Column208 { get; set; }
        public string? Column209 { get; set; }
        public string? Column210 { get; set; }
        public string? Column211 { get; set; }
        public string? Column212 { get; set; }
        public string? Column213 { get; set; }
        public string? Column214 { get; set; }
        public string? Column215 { get; set; }
        public string? Column216 { get; set; }
        public string? Column217 { get; set; }
        public string? Column218 { get; set; }
        public string? Column219 { get; set; }
        public string? Column220 { get; set; }
        public string? Column221 { get; set; }
        public string? Column222 { get; set; }
        public string? Column223 { get; set; }
        public string? Column224 { get; set; }
        public string? Column225 { get; set; }
        public string? Column226 { get; set; }
        public string? Column227 { get; set; }
        public string? Column228 { get; set; }
        public string? Column229 { get; set; }
        public string? Column230 { get; set; }
        public string? Column231 { get; set; }
        public string? Column232 { get; set; }
        public string? Column233 { get; set; }
        public string? Column234 { get; set; }
        public string? Column235 { get; set; }
        public string? Column236 { get; set; }
        public string? Column237 { get; set; }
        public string? Column238 { get; set; }
        public string? Column239 { get; set; }
        public string? Column240 { get; set; }
        public string? Column241 { get; set; }
        public string? Column242 { get; set; }
        public string? Column243 { get; set; }
        public string? Column244 { get; set; }
        public string? Column245 { get; set; }
        public string? Column246 { get; set; }
        public string? Column247 { get; set; }
        public string? Column248 { get; set; }
        public string? Column249 { get; set; }
        public string? Column250 { get; set; }
        public string? Column251 { get; set; }
        public string? Column252 { get; set; }
        public string? Column253 { get; set; }
        public string? Column254 { get; set; }
        public string? Column255 { get; set; }
        public string? Column256 { get; set; }
        public string? Column257 { get; set; }
        public string? Column258 { get; set; }
        public string? Column259 { get; set; }
        public string? Column260 { get; set; }
        public string? Column261 { get; set; }
        public string? Column262 { get; set; }
        public string? Column263 { get; set; }
        public string? Column264 { get; set; }
        public string? Column265 { get; set; }
        public string? Column266 { get; set; }
        public string? Column267 { get; set; }
        public string? Column268 { get; set; }
        public string? Column269 { get; set; }
        public string? Column270 { get; set; }
        public string? Column271 { get; set; }
        public string? Column272 { get; set; }
        public string? Column273 { get; set; }
        public string? Column274 { get; set; }
        public string? Column275 { get; set; }
        public string? Column276 { get; set; }
        public string? Column277 { get; set; }
        public string? Column278 { get; set; }
        public string? Column279 { get; set; }
        public string? Column280 { get; set; }
        public string? Column281 { get; set; }
        public string? Column282 { get; set; }
        public string? Column283 { get; set; }
        public string? Column284 { get; set; }
        public string? Column285 { get; set; }
        public string? Column286 { get; set; }
        public string? Column287 { get; set; }
        public string? Column288 { get; set; }
        public string? Column289 { get; set; }
        public string? Column290 { get; set; }
        public string? Column291 { get; set; }
        public string? Column292 { get; set; }
        public string? Column293 { get; set; }
        public string? Column294 { get; set; }
        public string? Column295 { get; set; }
        public string? Column296 { get; set; }
        public string? Column297 { get; set; }
        public string? Column298 { get; set; }
        public string? Column299 { get; set; }
        public string? Column300 { get; set; }
        public string? Column301 { get; set; }
        public string? Column302 { get; set; }
        public string? Column303 { get; set; }
        public string? Column304 { get; set; }
        public string? Column305 { get; set; }
        public string? Column306 { get; set; }
        public string? Column307 { get; set; }
        public string? Column308 { get; set; }
        public string? Column309 { get; set; }
        public string? Column310 { get; set; }
        public string? Column311 { get; set; }
        public string? Column312 { get; set; }
        public string? Column313 { get; set; }
        public string? Column314 { get; set; }
        public string? Column315 { get; set; }
        public string? Column316 { get; set; }
        public string? Column317 { get; set; }
        public string? Column318 { get; set; }
        public string? Column319 { get; set; }
        public string? Column320 { get; set; }
        public string? Column321 { get; set; }
        public string? Column322 { get; set; }
        public string? Column323 { get; set; }
        public string? Column324 { get; set; }
        public string? Column325 { get; set; }
        public string? Column326 { get; set; }
        public string? Column327 { get; set; }
        public string? Column328 { get; set; }
        public string? Column329 { get; set; }
        public string? Column330 { get; set; }
        public string? Column331 { get; set; }
        public string? Column332 { get; set; }
        public string? Column333 { get; set; }
        public string? Column334 { get; set; }
        public string? Column335 { get; set; }
        public string? Column336 { get; set; }
        public string? Column337 { get; set; }
        public string? Column338 { get; set; }
        public string? Column339 { get; set; }
        public string? Column340 { get; set; }
        public string? Column341 { get; set; }
        public string? Column342 { get; set; }
        public string? Column343 { get; set; }
        public string? Column344 { get; set; }
        public string? Column345 { get; set; }
        public string? Column346 { get; set; }
        public string? Column347 { get; set; }
        public string? Column348 { get; set; }
        public string? Column349 { get; set; }
        public string? Column350 { get; set; }
        public string? Column351 { get; set; }
        public string? Column352 { get; set; }
        public string? Column353 { get; set; }
        public string? Column354 { get; set; }
        public string? Column355 { get; set; }
        public string? Column356 { get; set; }
        public string? Column357 { get; set; }
        public string? Column358 { get; set; }
        public string? Column359 { get; set; }
        public string? Column360 { get; set; }
        public string? Column361 { get; set; }
        public string? Column362 { get; set; }
        public string? Column363 { get; set; }
        public string? Column364 { get; set; }
        public string? Column365 { get; set; }
        public string? Column366 { get; set; }
        public string? Column367 { get; set; }
        public string? Column368 { get; set; }
        public string? Column369 { get; set; }
        public string? Column370 { get; set; }
        public string? Column371 { get; set; }
        public string? Column372 { get; set; }
        public string? Column373 { get; set; }
        public string? Column374 { get; set; }
        public string? Column375 { get; set; }
        public string? Column376 { get; set; }
        public string? Column377 { get; set; }
        public string? Column378 { get; set; }
        public string? Column379 { get; set; }
        public string? Column380 { get; set; }
        public string? Column381 { get; set; }
        public string? Column382 { get; set; }
        public string? Column383 { get; set; }
        public string? Column384 { get; set; }
        public string? Column385 { get; set; }
        public string? Column386 { get; set; }
        public string? Column387 { get; set; }
        public string? Column388 { get; set; }
        public string? Column389 { get; set; }
        public string? Column390 { get; set; }
        public string? Column391 { get; set; }
        public string? Column392 { get; set; }
        public string? Column393 { get; set; }
        public string? Column394 { get; set; }
        public string? Column395 { get; set; }
        public string? Column396 { get; set; }
        public string? Column397 { get; set; }
        public string? Column398 { get; set; }
        public string? Column399 { get; set; }
        public string? Column400 { get; set; }
        public string? Column401 { get; set; }
        public string? Column402 { get; set; }
        public string? Column403 { get; set; }
        public string? Column404 { get; set; }
        public string? Column405 { get; set; }
        public string? Column406 { get; set; }
        public string? Column407 { get; set; }
        public string? Column408 { get; set; }
        public string? Column409 { get; set; }
        public string? Column410 { get; set; }
        public string? Column411 { get; set; }
        public string? Column412 { get; set; }
        public string? Column413 { get; set; }
        public string? Column414 { get; set; }
        public string? Column415 { get; set; }
        public string? Column416 { get; set; }
        public string? Column417 { get; set; }
        public string? Column418 { get; set; }
        public string? Column419 { get; set; }
        public string? Column420 { get; set; }
        public string? Column421 { get; set; }
        public string? Column422 { get; set; }
        public string? Column423 { get; set; }
        public string? Column424 { get; set; }
        public string? Column425 { get; set; }
        public string? Column426 { get; set; }
        public string? Column427 { get; set; }
        public string? Column428 { get; set; }
        public string? Column429 { get; set; }
        public string? Column430 { get; set; }
        public string? Column431 { get; set; }
        public string? Column432 { get; set; }
        public string? Column433 { get; set; }
        public string? Column434 { get; set; }
        public string? Column435 { get; set; }
        public string? Column436 { get; set; }
        public string? Column437 { get; set; }
        public string? Column438 { get; set; }
        public string? Column439 { get; set; }
        public string? Column440 { get; set; }
        public string? Column441 { get; set; }
        public string? Column442 { get; set; }
        public string? Column443 { get; set; }
        public string? Column444 { get; set; }
        public string? Column445 { get; set; }
        public string? Column446 { get; set; }
        public string? Column447 { get; set; }
        public string? Column448 { get; set; }
        public string? Column449 { get; set; }
        public string? Column450 { get; set; }
        public string? Column451 { get; set; }
        public string? Column452 { get; set; }
        public string? Column453 { get; set; }
        public string? Column454 { get; set; }
        public string? Column455 { get; set; }
        public string? Column456 { get; set; }
        public string? Column457 { get; set; }
        public string? Column458 { get; set; }
        public string? Column459 { get; set; }
        public string? Column460 { get; set; }
        public string? Column461 { get; set; }
        public string? Column462 { get; set; }
        public string? Column463 { get; set; }
        public string? Column464 { get; set; }
        public string? Column465 { get; set; }
        public string? Column466 { get; set; }
        public string? Column467 { get; set; }
        public string? Column468 { get; set; }
        public string? Column469 { get; set; }
        public string? Column470 { get; set; }
        public string? Column471 { get; set; }
        public string? Column472 { get; set; }
        public string? Column473 { get; set; }
        public string? Column474 { get; set; }
        public string? Column475 { get; set; }
        public string? Column476 { get; set; }
        public string? Column477 { get; set; }
        public string? Column478 { get; set; }
        public string? Column479 { get; set; }
        public string? Column480 { get; set; }
        public string? Column481 { get; set; }
        public string? Column482 { get; set; }
        public string? Column483 { get; set; }
        public string? Column484 { get; set; }
        public string? Column485 { get; set; }
        public string? Column486 { get; set; }
        public string? Column487 { get; set; }
        public string? Column488 { get; set; }
        public string? Column489 { get; set; }
        public string? Column490 { get; set; }
        public string? Column491 { get; set; }
        public string? Column492 { get; set; }
        public string? Column493 { get; set; }
        public string? Column494 { get; set; }
        public string? Column495 { get; set; }
        public string? Column496 { get; set; }
        public string? Column497 { get; set; }
        public string? Column498 { get; set; }
        public string? Column499 { get; set; }
        public string? Column500 { get; set; }
        public string? Column501 { get; set; }
        public string? Column502 { get; set; }
        public string? Column503 { get; set; }
        public string? Column504 { get; set; }
        public string? Column505 { get; set; }
        public string? Column506 { get; set; }
        public string? Column507 { get; set; }
        public string? Column508 { get; set; }
        public string? Column509 { get; set; }
        public string? Column510 { get; set; }
        public string? Column511 { get; set; }
        public string? Column512 { get; set; }
        public string? Column513 { get; set; }
        public string? Column514 { get; set; }
        public string? Column515 { get; set; }
        public string? Column516 { get; set; }
        public string? Column517 { get; set; }
        public string? Column518 { get; set; }
        public string? Column519 { get; set; }
        public string? Column520 { get; set; }
        public string? Column521 { get; set; }
        public string? Column522 { get; set; }
        public string? Column523 { get; set; }
        public string? Column524 { get; set; }
        public string? Column525 { get; set; }
        public string? Column526 { get; set; }
        public string? Column527 { get; set; }
        public string? Column528 { get; set; }
        public string? Column529 { get; set; }
        public string? Column530 { get; set; }
        public string? Column531 { get; set; }
        public string? Column532 { get; set; }
        public string? Column533 { get; set; }
        public string? Column534 { get; set; }
        public string? Column535 { get; set; }
        public string? Column536 { get; set; }
        public string? Column537 { get; set; }
        public string? Column538 { get; set; }
        public string? Column539 { get; set; }
        public string? Column540 { get; set; }
        public string? Column541 { get; set; }
        public string? Column542 { get; set; }
        public string? Column543 { get; set; }
        public string? Column544 { get; set; }
        public string? Column545 { get; set; }
        public string? Column546 { get; set; }
        public string? Column547 { get; set; }
        public string? Column548 { get; set; }
        public string? Column549 { get; set; }
        public string? Column550 { get; set; }
        public string? Column551 { get; set; }
        public string? Column552 { get; set; }
        public string? Column553 { get; set; }
        public string? Column554 { get; set; }
        public string? Column555 { get; set; }
        public string? Column556 { get; set; }
        public string? Column557 { get; set; }
        public string? Column558 { get; set; }
        public string? Column559 { get; set; }
        public string? Column560 { get; set; }
        public string? Column561 { get; set; }
        public string? Column562 { get; set; }
        public string? Column563 { get; set; }
        public string? Column564 { get; set; }
        public string? Column565 { get; set; }
        public string? Column566 { get; set; }
        public string? Column567 { get; set; }
        public string? Column568 { get; set; }
        public string? Column569 { get; set; }
        public string? Column570 { get; set; }
        public string? Column571 { get; set; }
        public string? Column572 { get; set; }
        public string? Column573 { get; set; }
        public string? Column574 { get; set; }
        public string? Column575 { get; set; }
        public string? Column576 { get; set; }
        public string? Column577 { get; set; }
        public string? Column578 { get; set; }
        public string? Column579 { get; set; }
        public string? Column580 { get; set; }
        public string? Column581 { get; set; }
        public string? Column582 { get; set; }
        public string? Column583 { get; set; }
        public string? Column584 { get; set; }
        public string? Column585 { get; set; }
        public string? Column586 { get; set; }
        public string? Column587 { get; set; }
        public string? Column588 { get; set; }
        public string? Column589 { get; set; }
        public string? Column590 { get; set; }
        public string? Column591 { get; set; }
        public string? Column592 { get; set; }
        public string? Column593 { get; set; }
        public string? Column594 { get; set; }
        public string? Column595 { get; set; }
        public string? Column596 { get; set; }
        public string? Column597 { get; set; }
        public string? Column598 { get; set; }
        public string? Column599 { get; set; }
        public string? Column600 { get; set; }
        public string? Column601 { get; set; }
        public string? Column602 { get; set; }
        public string? Column603 { get; set; }
        public string? Column604 { get; set; }
        public string? Column605 { get; set; }
        public string? Column606 { get; set; }
        public string? Column607 { get; set; }
        public string? Column608 { get; set; }
        public string? Column609 { get; set; }
        public string? Column610 { get; set; }
        public string? Column611 { get; set; }
        public string? Column612 { get; set; }
        public string? Column613 { get; set; }
        public string? Column614 { get; set; }
        public string? Column615 { get; set; }
        public string? Column616 { get; set; }
        public string? Column617 { get; set; }
        public string? Column618 { get; set; }
        public string? Column619 { get; set; }
        public string? Column620 { get; set; }
        public string? Column621 { get; set; }
        public string? Column622 { get; set; }
        public string? Column623 { get; set; }
        public string? Column624 { get; set; }
        public string? Column625 { get; set; }
        public string? Column626 { get; set; }
        public string? Column627 { get; set; }
        public string? Column628 { get; set; }
        public string? Column629 { get; set; }
        public string? Column630 { get; set; }
        public string? Column631 { get; set; }
        public string? Column632 { get; set; }
        public string? Column633 { get; set; }
        public string? Column634 { get; set; }
        public string? Column635 { get; set; }
        public string? Column636 { get; set; }
        public string? Column637 { get; set; }
        public string? Column638 { get; set; }
        public string? Column639 { get; set; }
        public string? Column640 { get; set; }
        public string? Column641 { get; set; }
        public string? Column642 { get; set; }
        public string? Column643 { get; set; }
        public string? Column644 { get; set; }
        public string? Column645 { get; set; }
        public string? Column646 { get; set; }
        public string? Column647 { get; set; }
        public string? Column648 { get; set; }
        public string? Column649 { get; set; }
        public string? Column650 { get; set; }
        public string? Column651 { get; set; }
        public string? Column652 { get; set; }
        public string? Column653 { get; set; }
        public string? Column654 { get; set; }
        public string? Column655 { get; set; }
        public string? Column656 { get; set; }
        public string? Column657 { get; set; }
        public string? Column658 { get; set; }
        public string? Column659 { get; set; }
        public string? Column660 { get; set; }
        public string? Column661 { get; set; }
        public string? Column662 { get; set; }
        public string? Column663 { get; set; }
        public string? Column664 { get; set; }
        public string? Column665 { get; set; }
        public string? Column666 { get; set; }
        public string? Column667 { get; set; }
        public string? Column668 { get; set; }
        public string? Column669 { get; set; }
        public string? Column670 { get; set; }
        public string? Column671 { get; set; }
        public string? Column672 { get; set; }
        public string? Column673 { get; set; }
        public string? Column674 { get; set; }
        public string? Column675 { get; set; }
        public string? Column676 { get; set; }
        public string? Column677 { get; set; }
        public string? Column678 { get; set; }
        public string? Column679 { get; set; }
        public string? Column680 { get; set; }
        public string? Column681 { get; set; }
        public string? Column682 { get; set; }
        public string? Column683 { get; set; }
        public string? Column684 { get; set; }
        public string? Column685 { get; set; }
        public string? Column686 { get; set; }
        public string? Column687 { get; set; }
        public string? Column688 { get; set; }
        public string? Column689 { get; set; }
        public string? Column690 { get; set; }
        public string? Column691 { get; set; }
        public string? Column692 { get; set; }
        public string? Column693 { get; set; }
        public string? Column694 { get; set; }
        public string? Column695 { get; set; }
        public string? Column696 { get; set; }
        public string? Column697 { get; set; }
        public string? Column698 { get; set; }
        public string? Column699 { get; set; }
        public string? Column700 { get; set; }
        public string? Column701 { get; set; }
        public string? Column702 { get; set; }
        public string? Column703 { get; set; }
        public string? Column704 { get; set; }
        public string? Column705 { get; set; }
        public string? Column706 { get; set; }
        public string? Column707 { get; set; }
        public string? Column708 { get; set; }
        public string? Column709 { get; set; }
        public string? Column710 { get; set; }
        public string? Column711 { get; set; }
        public string? Column712 { get; set; }
        public string? Column713 { get; set; }
        public string? Column714 { get; set; }
        public string? Column715 { get; set; }
        public string? Column716 { get; set; }
        public string? Column717 { get; set; }
        public string? Column718 { get; set; }
        public string? Column719 { get; set; }
        public string? Column720 { get; set; }
        public string? Column721 { get; set; }
        public string? Column722 { get; set; }
        public string? Column723 { get; set; }
        public string? Column724 { get; set; }
        public string? Column725 { get; set; }
        public string? Column726 { get; set; }
        public string? Column727 { get; set; }
        public string? Column728 { get; set; }
        public string? Column729 { get; set; }
        public string? Column730 { get; set; }
        public string? Column731 { get; set; }
        public string? Column732 { get; set; }
        public string? Column733 { get; set; }
        public string? Column734 { get; set; }
        public string? Column735 { get; set; }
        public string? Column736 { get; set; }
        public string? Column737 { get; set; }
        public string? Column738 { get; set; }
        public string? Column739 { get; set; }
        public string? Column740 { get; set; }
        public string? Column741 { get; set; }
        public string? Column742 { get; set; }
        public string? Column743 { get; set; }
        public string? Column744 { get; set; }
        public string? Column745 { get; set; }
        public string? Column746 { get; set; }
        public string? Column747 { get; set; }
        public string? Column748 { get; set; }
        public string? Column749 { get; set; }
        public string? Column750 { get; set; }
        public string? Column751 { get; set; }
        public string? Column752 { get; set; }
        public string? Column753 { get; set; }
        public string? Column754 { get; set; }
        public string? Column755 { get; set; }
        public string? Column756 { get; set; }
        public string? Column757 { get; set; }
        public string? Column758 { get; set; }
        public string? Column759 { get; set; }
        public string? Column760 { get; set; }
        public string? Column761 { get; set; }
        public string? Column762 { get; set; }
        public string? Column763 { get; set; }
        public string? Column764 { get; set; }
        public string? Column765 { get; set; }
        public string? Column766 { get; set; }
        public string? Column767 { get; set; }
        public string? Column768 { get; set; }
        public string? Column769 { get; set; }
        public string? Column770 { get; set; }
        public string? Column771 { get; set; }
        public string? Column772 { get; set; }
        public string? Column773 { get; set; }
        public string? Column774 { get; set; }
        public string? Column775 { get; set; }
        public string? Column776 { get; set; }
        public string? Column777 { get; set; }
        public string? Column778 { get; set; }
        public string? Column779 { get; set; }
        public string? Column780 { get; set; }
        public string? Column781 { get; set; }
        public string? Column782 { get; set; }
        public string? Column783 { get; set; }
        public string? Column784 { get; set; }
        public string? Column785 { get; set; }
        public string? Column786 { get; set; }
        public string? Column787 { get; set; }
        public string? Column788 { get; set; }
        public string? Column789 { get; set; }
        public string? Column790 { get; set; }
        public string? Column791 { get; set; }
        public string? Column792 { get; set; }
        public string? Column793 { get; set; }
        public string? Column794 { get; set; }
        public string? Column795 { get; set; }
        public string? Column796 { get; set; }
        public string? Column797 { get; set; }
        public string? Column798 { get; set; }
        public string? Column799 { get; set; }
        public string? Column800 { get; set; }
        public string? Column801 { get; set; }
        public string? Column802 { get; set; }
        public string? Column803 { get; set; }
        public string? Column804 { get; set; }
        public string? Column805 { get; set; }
        public string? Column806 { get; set; }
        public string? Column807 { get; set; }
        public string? Column808 { get; set; }
        public string? Column809 { get; set; }
        public string? Column810 { get; set; }
        public string? Column811 { get; set; }
        public string? Column812 { get; set; }
        public string? Column813 { get; set; }
        public string? Column814 { get; set; }
        public string? Column815 { get; set; }
        public string? Column816 { get; set; }
        public string? Column817 { get; set; }
        public string? Column818 { get; set; }
        public string? Column819 { get; set; }
        public string? Column820 { get; set; }
        public string? Column821 { get; set; }
        public string? Column822 { get; set; }
        public string? Column823 { get; set; }
        public string? Column824 { get; set; }
        public string? Column825 { get; set; }
        public string? Column826 { get; set; }
        public string? Column827 { get; set; }
        public string? Column828 { get; set; }
        public string? Column829 { get; set; }
        public string? Column830 { get; set; }
        public string? Column831 { get; set; }
        public string? Column832 { get; set; }
        public string? Column833 { get; set; }
        public string? Column834 { get; set; }
        public string? Column835 { get; set; }
        public string? Column836 { get; set; }
        public string? Column837 { get; set; }
        public string? Column838 { get; set; }
        public string? Column839 { get; set; }
        public string? Column840 { get; set; }
        public string? Column841 { get; set; }
        public string? Column842 { get; set; }
        public string? Column843 { get; set; }
        public string? Column844 { get; set; }
        public string? Column845 { get; set; }
        public string? Column846 { get; set; }
        public string? Column847 { get; set; }
        public string? Column848 { get; set; }
        public string? Column849 { get; set; }
        public string? Column850 { get; set; }
        public string? Column851 { get; set; }
        public string? Column852 { get; set; }
        public string? Column853 { get; set; }
        public string? Column854 { get; set; }
        public string? Column855 { get; set; }
        public string? Column856 { get; set; }
        public string? Column857 { get; set; }
        public string? Column858 { get; set; }
        public string? Column859 { get; set; }
        public string? Column860 { get; set; }
        public string? Column861 { get; set; }
        public string? Column862 { get; set; }
        public string? Column863 { get; set; }
        public string? Column864 { get; set; }
        public string? Column865 { get; set; }
        public string? Column866 { get; set; }
        public string? Column867 { get; set; }
        public string? Column868 { get; set; }
        public string? Column869 { get; set; }
        public string? Column870 { get; set; }
        public string? Column871 { get; set; }
        public string? Column872 { get; set; }
        public string? Column873 { get; set; }
        public string? Column874 { get; set; }
        public string? Column875 { get; set; }
        public string? Column876 { get; set; }
        public string? Column877 { get; set; }
        public string? Column878 { get; set; }
        public string? Column879 { get; set; }
        public string? Column880 { get; set; }
        public string? Column881 { get; set; }
        public string? Column882 { get; set; }
        public string? Column883 { get; set; }
        public string? Column884 { get; set; }
        public string? Column885 { get; set; }
        public string? Column886 { get; set; }
        public string? Column887 { get; set; }
        public string? Column888 { get; set; }
        public string? Column889 { get; set; }
        public string? Column890 { get; set; }
        public string? Column891 { get; set; }
        public string? Column892 { get; set; }
        public string? Column893 { get; set; }
        public string? Column894 { get; set; }
        public string? Column895 { get; set; }
        public string? Column896 { get; set; }
        public string? Column897 { get; set; }
        public string? Column898 { get; set; }
        public string? Column899 { get; set; }
        public string? Column900 { get; set; }
        public string? Column901 { get; set; }
        public string? Column902 { get; set; }
        public string? Column903 { get; set; }
        public string? Column904 { get; set; }
        public string? Column905 { get; set; }
        public string? Column906 { get; set; }
        public string? Column907 { get; set; }
        public string? Column908 { get; set; }
        public string? Column909 { get; set; }
        public string? Column910 { get; set; }
        public string? Column911 { get; set; }
        public string? Column912 { get; set; }
        public string? Column913 { get; set; }
        public string? Column914 { get; set; }
        public string? Column915 { get; set; }
        public string? Column916 { get; set; }
        public string? Column917 { get; set; }
        public string? Column918 { get; set; }
        public string? Column919 { get; set; }
        public string? Column920 { get; set; }
        public string? Column921 { get; set; }
        public string? Column922 { get; set; }
        public string? Column923 { get; set; }
        public string? Column924 { get; set; }
        public string? Column925 { get; set; }
        public string? Column926 { get; set; }
        public string? Column927 { get; set; }
        public string? Column928 { get; set; }
        public string? Column929 { get; set; }
        public string? Column930 { get; set; }
        public string? Column931 { get; set; }
        public string? Column932 { get; set; }
        public string? Column933 { get; set; }
        public string? Column934 { get; set; }
        public string? Column935 { get; set; }
        public string? Column936 { get; set; }
        public string? Column937 { get; set; }
        public string? Column938 { get; set; }
        public string? Column939 { get; set; }
        public string? Column940 { get; set; }
        public string? Column941 { get; set; }
        public string? Column942 { get; set; }
        public string? Column943 { get; set; }
        public string? Column944 { get; set; }
        public string? Column945 { get; set; }
        public string? Column946 { get; set; }
        public string? Column947 { get; set; }
        public string? Column948 { get; set; }
        public string? Column949 { get; set; }
        public string? Column950 { get; set; }
        public string? Column951 { get; set; }
        public string? Column952 { get; set; }
        public string? Column953 { get; set; }
        public string? Column954 { get; set; }
        public string? Column955 { get; set; }
        public string? Column956 { get; set; }
        public string? Column957 { get; set; }
        public string? Column958 { get; set; }
        public string? Column959 { get; set; }
        public string? Column960 { get; set; }
        public string? Column961 { get; set; }
        public string? Column962 { get; set; }
        public string? Column963 { get; set; }
        public string? Column964 { get; set; }
        public string? Column965 { get; set; }
        public string? Column966 { get; set; }
        public string? Column967 { get; set; }
        public string? Column968 { get; set; }
        public string? Column969 { get; set; }
        public string? Column970 { get; set; }
        public string? Column971 { get; set; }
        public string? Column972 { get; set; }
        public string? Column973 { get; set; }
        public string? Column974 { get; set; }
        public string? Column975 { get; set; }
        public string? Column976 { get; set; }
        public string? Column977 { get; set; }
        public string? Column978 { get; set; }
        public string? Column979 { get; set; }
        public string? Column980 { get; set; }
        public string? Column981 { get; set; }
        public string? Column982 { get; set; }
        public string? Column983 { get; set; }
        public string? Column984 { get; set; }
        public string? Column985 { get; set; }
        public string? Column986 { get; set; }
        public string? Column987 { get; set; }
        public string? Column988 { get; set; }
        public string? Column989 { get; set; }
        public string? Column990 { get; set; }
        public string? Column991 { get; set; }
        public string? Column992 { get; set; }
        public string? Column993 { get; set; }
        public string? Column994 { get; set; }
        public string? Column995 { get; set; }
        public string? Column996 { get; set; }
        public string? Column997 { get; set; }
        public string? Column998 { get; set; }
        public string? Column999 { get; set; }
    }
}
