using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class RawShipmentHdr
    {
        public int ImportId { get; set; }
        public string? SalesOrderNumber { get; set; }
        public string? SalesOrderItem { get; set; }
        public string? HigherLevelItem { get; set; }
        public string? DeliveryNumber { get; set; }
        public string? DeliveryType { get; set; }
        public string? DeliveryCreatedOn { get; set; }
        public string? CompleteDelivery { get; set; }
        public string? ShipDate { get; set; }
        public string? OrderType { get; set; }
        public string? OrderReason { get; set; }
        public string? MaterialKey { get; set; }
        public string? MaterialText { get; set; }
        public string? SalesDocumentItemCategory { get; set; }
        public string? CustomerPoNumber { get; set; }
        public string? CumulativeOrderQuantity { get; set; }
        public string? MaterialEccnText { get; set; }
        public string? MaterialHtsText { get; set; }
        public string? ShipmentsQuantity { get; set; }
        public string? ShipmentsNetValue { get; set; }
        public string? ShipmentsCogsValue { get; set; }
        public string? ShipmentsListValue { get; set; }
        public string? Plant { get; set; }
        public string? PlantMediumText { get; set; }
        public string? PlantCountryText { get; set; }
        public string? BillToPartyKey { get; set; }
        public string? BillToParty { get; set; }
        public string? BillToPartyStreetNameKey { get; set; }
        public string? BillToPartyBasStreet2Key { get; set; }
        public string? BillToPartyBasStreet3Key { get; set; }
        public string? BillToPartyBasStreet4Key { get; set; }
        public string? BillToPartyBasStreet5Key { get; set; }
        public string? BillToPartyLocationKey { get; set; }
        public string? BillToPartyRegionText { get; set; }
        public string? BillToPartyBasCityDistrictKey { get; set; }
        public string? BillToPartyPostalCodeKey { get; set; }
        public string? BillToPartyCountry { get; set; }
        public string? DeliveryShipToPartyKey { get; set; }
        public string? DeliveryShipToParty { get; set; }
        public string? DeliveryShipToPartyStreetNameKey { get; set; }
        public string? DeliveryShipToPartyBasStreet2Key { get; set; }
        public string? DeliveryShipToPartyBasStreet3Key { get; set; }
        public string? DeliveryShipToPartyBasStreet4Key { get; set; }
        public string? DeliveryShipToPartyBasStreet5Key { get; set; }
        public string? DeliveryShipToPartyLocationKey { get; set; }
        public string? DeliveryShipToPartyRegionText { get; set; }
        public string? DeliveryShipToPartyBasCityDistrictKey { get; set; }
        public string? DeliveryShipToPartyPostalCodeKey { get; set; }
        public string? DeliveryShipToPartyCountryText { get; set; }
        public string? EndUserKey { get; set; }
        public string? EndUser { get; set; }
        public string? EndUserStreetNameKey { get; set; }
        public string? EndUserBasStreet2Key { get; set; }
        public string? EndUserBasStreet3Key { get; set; }
        public string? EndUserBasStreet4Key { get; set; }
        public string? EndUserBasStreet5Key { get; set; }
        public string? EndUserLocationKey { get; set; }
        public string? EndUserRegionText { get; set; }
        public string? EndUserBasCityDistrictKey { get; set; }
        public string? EndUserPostalCodeKey { get; set; }
        public string? EndUserCountryText { get; set; }
        public string? SoldToPartyKey { get; set; }
        public string? SoldToParty { get; set; }
        public string? SoldToPartyStreetNameKey { get; set; }
        public string? SoldToPartyBasStreet2Key { get; set; }
        public string? SoldToPartyBasStreet3Key { get; set; }
        public string? SoldToPartyBasStreet4Key { get; set; }
        public string? SoldToPartyBasStreet5Key { get; set; }
        public string? SoldToPartyLocationKey { get; set; }
        public string? SoldToPartyRegionText { get; set; }
        public string? SoldToPartyBasCityDistrictKey { get; set; }
        public string? SoldToPartyPostalCodeKey { get; set; }
        public string? SoldToPartyCountryText { get; set; }
        public string? FreightForwarder1Key { get; set; }
        public string? FreightForwarder1 { get; set; }
        public string? FreightForwarder1StreetNameKey { get; set; }
        public string? FreightForwarder1LocationKey { get; set; }
        public string? FreightForwarder1CountryText { get; set; }
        public string? PodControl { get; set; }
        public string? PodStatusOnHeader { get; set; }
        public string? PodStatusOnItem { get; set; }
        public string? TrackingNumber { get; set; }
        public string? MaterialGrossWeightKey { get; set; }
        public string? MaterialNetWeightKey { get; set; }
        public string? MaterialWeightUnitKey { get; set; }
        public string? MaterialWeightUnitText { get; set; }
        public string? Incoterms1 { get; set; }
        public string? Incoterms2 { get; set; }
        public string? ShippingType { get; set; }
        public string? ShippingNoteText { get; set; }
        public string? VarExtLincenseNum { get; set; }
        public string? VarLegRegLegalCtrl { get; set; }
        public string? VarLicenseAppliedDate { get; set; }
        public string? VarLicenseNumber { get; set; }
        public string? VarLicenseType { get; set; }
        public string? VarLicenseValidFrom { get; set; }
        public string? VarLicValidTo { get; set; }
        public DateTime? ImportDate { get; set; }
        public string? ImportStatus { get; set; }
    }
}
