using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class RmaLinesJunjul2018
    {
        public string? ComplaintsNo { get; set; }
        public string? RmaItemNumber0crmNumint { get; set; }
        public string? HeaderStatus { get; set; }
        public string? ItemStatus { get; set; }
        public string? RmaCreateDate { get; set; }
        public string? ItemCreateDate { get; set; }
        public string? ValuationType { get; set; }
        public string? RmaItemType { get; set; }
        public string? RmaItemTypeKey { get; set; }
        public string? ServiceReqNo { get; set; }
        public string? DefectSerialNo { get; set; }
        public string? DefectProductIdKey { get; set; }
        public string? DefectProductId { get; set; }
        public string? DefectProductIdEccnKey { get; set; }
        public string? DefectProductIdHtsKey { get; set; }
        public string? DefectProductIdOverLengthPartNumKey { get; set; }
        public string? ReplaceSerialNo { get; set; }
        public string? ReplaceProductId0materialKey { get; set; }
        public string? ReplaceProductId0material { get; set; }
        public string? ReplaceEccn { get; set; }
        public string? ReplaceProductId0materialHtsKey { get; set; }
        public string? ReplaceProductId0materialOverLengthPartNumKey { get; set; }
        public string? PlantKey { get; set; }
        public string? PlantText { get; set; }
        public string? StorageLocationKey { get; set; }
        public string? StorageLocationText { get; set; }
        public string? EndCustomerKey { get; set; }
        public string? EndCustomerName { get; set; }
        public string? EndCustomerBasStreetKey { get; set; }
        public string? EndCustomerBasStreet2Key { get; set; }
        public string? EndCustomerBasStreet3Key { get; set; }
        public string? EndCustomerBasStreet4Key { get; set; }
        public string? EndCustomerCity { get; set; }
        public string? EndCustomerRegionText { get; set; }
        public string? EndCustomerCountryKey { get; set; }
        public string? EndCustomerCountryText { get; set; }
        public string? EndCustomerBasPostalCodeKey { get; set; }
        public string? AssociatedContactKey { get; set; }
        public string? AssociatedContactName { get; set; }
        public string? AssociatedContactBasStreetKey { get; set; }
        public string? AssociatedContactBasStreet2Key { get; set; }
        public string? AssociatedContactBasStreet3Key { get; set; }
        public string? AssociatedContactBasStreet4Key { get; set; }
        public string? AssociatedContactCity { get; set; }
        public string? AssociatedContactRegionText { get; set; }
        public string? AssociatedContactCountryKey { get; set; }
        public string? AssociatedContactCountryText { get; set; }
        public string? AssociatedContactBasPostalCodeKey { get; set; }
        public string? ShipDate { get; set; }
        public string? TrackingNo { get; set; }
        public string? ShipToSiteKey { get; set; }
        public string? ShipToSiteName { get; set; }
        public string? ShipToAddr1Key { get; set; }
        public string? ShipToAddr2Key { get; set; }
        public string? ShipToCityKey { get; set; }
        public string? ShipToSiteRegionKey { get; set; }
        public string? ShipToSiteRegion { get; set; }
        public string? ShipToSiteCountryKey { get; set; }
        public string? ShipToSitePostalCodeKey { get; set; }
        public string? InstalledAtKey { get; set; }
        public string? InstalledAtName { get; set; }
        public string? InstalledAtBasStreetKey { get; set; }
        public string? InstalledAtBasStreet2Key { get; set; }
        public string? InstalledAtBasStreet3Key { get; set; }
        public string? InstalledAtBasStreet4Key { get; set; }
        public string? InstalledAtCity { get; set; }
        public string? InstalledAtRegionText { get; set; }
        public string? InstalledAtCountryKey { get; set; }
        public string? InstalledAtCountryText { get; set; }
        public string? InstalledAtBasPostalCodeKey { get; set; }
        public string? CustomsDeclarationNo { get; set; }
        public string? CustomsDeclCreateDt { get; set; }
        public string? Coo { get; set; }
        public string? DeliveryNumber { get; set; }
        public string? DeliveryCreateDate { get; set; }
        public string? LegalRegulation { get; set; }
        public string? LicenseValidFrom { get; set; }
        public string? LicenseValidTo { get; set; }
        public string? LicenseAppliedDate { get; set; }
        public string? LicenseNumber { get; set; }
        public string? LicenseType { get; set; }
        public string? ExtLicence { get; set; }
        public string? GoodsSupplier { get; set; }
        public string? GoodsSupplierKey { get; set; }
        public string? Vendor { get; set; }
        public string? VendorKey { get; set; }
        public string? ShipToPartyKey { get; set; }
        public string? GtsShipToKey { get; set; }
        public string? GtsShipToAddressKey { get; set; }
        public string? GtsShipToAddr1Key { get; set; }
        public string? GtsShipToAddr2Key { get; set; }
        public string? GtsShipToCity { get; set; }
        public string? GtsShipToCountry { get; set; }
        public string? BillToPartyKey { get; set; }
        public string? GtsBillToKey { get; set; }
        public string? GtsBillToAddressKey { get; set; }
        public string? GtsBillToAddr1Key { get; set; }
        public string? GtsBillToAddr2Key { get; set; }
        public string? GtsBillToCity { get; set; }
        public string? GtsBillToCountry { get; set; }
        public string? ExporterKey { get; set; }
        public string? GtsExporterAddressKey { get; set; }
        public string? ExporterAddr1Key { get; set; }
        public string? ExporterAddr2Key { get; set; }
        public string? ExporterCity { get; set; }
        public string? ExporterCountry { get; set; }
        public string? CustomsValuation { get; set; }
    }
}
