using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class TcProfileForm
    {
        public int Id { get; set; }
        public string? SubFn { get; set; }
        public string? SubLn { get; set; }
        public string? JobTitle { get; set; }
        public string? CpName { get; set; }
        public string? SubEmail { get; set; }
        public string? JVarid { get; set; }
        public string? Quote { get; set; }
        public DateTime? QDate { get; set; }
        public string? Po { get; set; }
        public string? So { get; set; }
        public string? DCompname { get; set; }
        public string? DStreet { get; set; }
        public string? DCity { get; set; }
        public string? DState { get; set; }
        public string? DPostal { get; set; }
        public string? DCty { get; set; }
        public string? DistiResl { get; set; }
        public string? EuCompname { get; set; }
        public string? EuStreet { get; set; }
        public string? EuCity { get; set; }
        public string? EuState { get; set; }
        public string? EuPostal { get; set; }
        public string? EuCty { get; set; }
        public string? EuName { get; set; }
        public string? EuEmail { get; set; }
        public string? EuUrl { get; set; }
        public string? EuUrlText { get; set; }
        public string? EuBussFn { get; set; }
        public string? EuOffering { get; set; }
        public string? OpCompname { get; set; }
        public string? OpStreet { get; set; }
        public string? OpCity { get; set; }
        public string? OpState { get; set; }
        public string? OpPostal { get; set; }
        public string? OpCty { get; set; }
        public string? OpName { get; set; }
        public string? OpEmail { get; set; }
        public string? OpUrl { get; set; }
        public string? Neu1Compname { get; set; }
        public string? Neu1Street { get; set; }
        public string? Neu1City { get; set; }
        public string? Neu1State { get; set; }
        public string? Neu1Postal { get; set; }
        public string? Neu1Cty { get; set; }
        public string? Neu1Name { get; set; }
        public string? Neu1Email { get; set; }
        public string? Neu1Url { get; set; }
        public string? Neu2Compname { get; set; }
        public string? Neu2Street { get; set; }
        public string? Neu2City { get; set; }
        public string? Neu2State { get; set; }
        public string? Neu2Postal { get; set; }
        public string? Neu2Cty { get; set; }
        public string? Neu2Name { get; set; }
        public string? Neu2Email { get; set; }
        public string? Neu2Url { get; set; }
        public string? Neu3Compname { get; set; }
        public string? Neu3Street { get; set; }
        public string? Neu3City { get; set; }
        public string? Neu3State { get; set; }
        public string? Neu3Postal { get; set; }
        public string? Neu3Cty { get; set; }
        public string? Neu3Name { get; set; }
        public string? Neu3Email { get; set; }
        public string? Neu3Url { get; set; }
        public string? Neu4Compname { get; set; }
        public string? Neu4Street { get; set; }
        public string? Neu4City { get; set; }
        public string? Neu4State { get; set; }
        public string? Neu4Postal { get; set; }
        public string? Neu4Cty { get; set; }
        public string? Neu4Name { get; set; }
        public string? Neu4Email { get; set; }
        public string? Neu4Url { get; set; }
        public string? EuQ1 { get; set; }
        public string? EuQ2 { get; set; }
        public string? EuQ3 { get; set; }
        public string? S1Compname { get; set; }
        public string? S1Street { get; set; }
        public string? S1City { get; set; }
        public string? S1State { get; set; }
        public string? S1Postal { get; set; }
        public string? S1Cty { get; set; }
        public string? S1Url { get; set; }
        public string? S2Compname { get; set; }
        public string? S2Street { get; set; }
        public string? S2City { get; set; }
        public string? S2State { get; set; }
        public string? S2Postal { get; set; }
        public string? S2Cty { get; set; }
        public string? S2Url { get; set; }
        public string? S3Compname { get; set; }
        public string? S3Street { get; set; }
        public string? S3City { get; set; }
        public string? S3State { get; set; }
        public string? S3Postal { get; set; }
        public string? S3Cty { get; set; }
        public string? S3Url { get; set; }
        public string? S4Compname { get; set; }
        public string? S4Street { get; set; }
        public string? S4City { get; set; }
        public string? S4State { get; set; }
        public string? S4Postal { get; set; }
        public string? S4Cty { get; set; }
        public string? S4Url { get; set; }
        public string? S5Compname { get; set; }
        public string? S5Street { get; set; }
        public string? S5City { get; set; }
        public string? S5State { get; set; }
        public string? S5Postal { get; set; }
        public string? S5Cty { get; set; }
        public string? S5Url { get; set; }
        public string? CpCompname { get; set; }
        public string? AuthRepreName { get; set; }
        public string? AuthRepreJob { get; set; }
        public DateTime? AckDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public byte[]? Document { get; set; }
        public byte[]? Document1 { get; set; }
        public string? EliasCopy { get; set; }
    }
}
